sudo: required
services:
  - docker

before_install:
  - docker build -t root/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run root/react-test npm test -- --coverage
after_success:
  - docker build -t root/multi-client ./client
  - docker build -t root/multi-nginx ./nginx
  - docker build -t root/multi-server ./server
  - docker build -t root/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push root/multi-client
  - docker push root/multi-nginx
  - docker push root/multi-server
  - docker push root/multi-worker
